### ISSUE TITLE
Le CTCSS affiché dans les profils radio n'est pas le bon

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#1]
Voir images
![2020-11-17_22-24-04](https://user-images.githubusercontent.com/74626991/99452458-d5a6ba80-2923-11eb-966f-01c302c69d21.jpg)
![2020-11-17_22-24-35](https://user-images.githubusercontent.com/74626991/99452461-d63f5100-2923-11eb-90eb-3cd4278638d4.jpg)

**Comment by marcbat** [comment]
Je vais afficher les deux CTCSS

**Comment by marcbat** [comment]
Corrigé dans la release 0.9.2

**Comment by nmermoud** [comment]
Déployé testé > ok :-)
