### ISSUE TITLE
Mise à jour version preview de 0.14.0-alpha.23 vers +

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#14]
Je suis en 0.14.0-alpha.23 à ce stade la version 0.14.0-alpha.52 est disponible.
Dans l'interface web sous "Mise à jour" quand je clique sur "Inclure les versions preview" ça ne m'affiche plus les versions preview et j'ai un message de reload en bas de la page "An error has occurred. This application may no longer respond until reloaded. Reload".
Le reload ré-affiche la page "Mise à jour" sans les version preview.

**Comment by nmermoud** [comment]
Salut Marc.
J'ai migré manuellement en Svxlink Manager 0.14.0-alpha.52 et le problème a disparu.
Vu qu'on est en alpha ça n'a pas d'importance je clos ce ticket
As-tu corrigé quelque chose entre la .23 et la .52 ?

**Comment by marcbat** [comment]
@nmermoud , oui, j'ai travaillé encore sur la fonction de mise à jour. 
Dans certain cas, le fichier d'update faisait 0kb après téléchargement. J'ai donc ajouté une fonction de checksum pour être sûr de l'intégrité du fichier avant de permettre le lancement d'une mise à jour.
