### ISSUE TITLE
Problème de mise à jour depuis la version 1.0.0-beta.1

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#26]
Il n'est plus possible de mettre à jour de la Release-1.0.0-beta.1 vers la Release-1.0.0-beta.2+1

Le message "An error has occurred. This application may no longer respond until reloaded. Reload" s'affiche en bas de page quand on tente d'obtenir la mise à jour.

À noter que si on tente d'obtenir une ancienne version il n'y a pas de problème.

Nat

**Comment by marcbat** [comment]
Corrigé en 1.0.0-beta.3
