### ISSUE TITLE
On ne peut pas changer de profil radio si on est pas dans un salon

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#29]
Si on change de profil radio alors qu'on est pas dans un salon ou qu'on est sur le salon répéteur perroquet, une erreur s'affiche : 
An error has occurred

**Comment by marcbat** [comment]
Je n'arrive pas à reproduire ce bug. De mon côté, ça a l'air de fonctionner. 
Peux tu tester à nouveau sur la 1.1.0-beta.1?

**Comment by nmermoud** [comment]
Plus reproductible
