### ISSUE TITLE
Le script de mise à jour doit prendre en compte les annonces de salon personalisées

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#30]
Recopier le dossier /etc/SvxlinkManager.bak/Sounds/ vers le dossier original pendant la mise à jour.

**Comment by marcbat** [comment]
Effectivement, on a oublié ce point. J'y avais pensé dans le cadre de l'export / import de configuration. Le mieux à terme, c'est que les fichiers soit contenus dan la base de donnée. Comme ça, le backup, c'est la base de donnée tout simplement.

**Comment by marcbat** [comment]
Je pense que je vais faire ça pour la release 1.2.0. En intégrant les fichiers audio dans la base de donnée.

**Comment by marcbat** [comment]
Les fichiers ont été ajoutés en base de donnée. Les defaults et customs. Résolu en 1.2.0
