### ISSUE TITLE
DTMF non reconnue

### ISSUE THREAD

**Issue by boucheronb** [marcbat/svxlinkmanager#32]
Il semble que le code DTMF 95 (Perroquet) ne soient plus reconnus. 
Lors de l'envoie du DTMF 95, l'annonce "9 5 commande inconnue" est donnée
Les autre codes testés comme 104 ou 100 sont OK

**Comment by marcbat** [comment]
Effectivement, le processus est un peu différent pour Echolink que pour les salons classiques. Je vais vérifier ça.

**Comment by marcbat** [comment]
Le bug est corrigé via le ticket #45 . Disponible en3.1.0
