### ISSUE TITLE
[svxlink.conf] La variable TIMESTAMP_FORMAT semble ne pas être interpretée dans les annonces d'heures

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#35]
Toute les heures l'annonce "long identification" est lancée et annonce l'indicatif et l'heure.
Depuis le passage à l'image UBUNTU l'annonce ne se fait plus en mode "24H" mais en "AM/PM"

D’après le fichier de config svxlink et en référence au man de ce dernier l'annonce devrait se baser sur les locale 

Pour cette partie le fichier de config svxlink.conf est paramétré comme ça : 

`TIMESTAMP_FORMAT=%c`

La locale interprétée / utilisée par cette config est bien LC_TIME="fr_FR.UTF-8" et devrait donc faire une annonce en mode 24H

Si on change la valeur TIMESTAMP_FORMAT pour spécifier un autre format celui-ci n'est pas interprété non plus.

Marc si tu as une idée dis moi :-)

**Comment by marcbat** [comment]
D'après la doc, TIMESTAMP_FORMAT n'influe que sur le format de date écrit dans les fichiers logs. Je vais voir comment l'annonce de l'heure est construite.

**Comment by nmermoud** [comment]
Il y a d’autres choses que j’ai remarqué 
L’annonce né donne plus la fréquence et le tone du hotspot.
Peut être une piste...
Je cherche aussi.

**Comment by nmermoud** [comment]
J'ai récupérer les dossiers pésents dans "/usr/share/svxlink/sounds" de la spotnik v4.1 originale afin de vérifier qu'il ne manquait pas des sons dans notre image.
Je confirme que ça ne change rien au problème.

**Comment by marcbat** [comment]
@nmermoud Je te laisse clore ce ticket quand tu as intégré le fichier à l'image.

**Comment by nmermoud** [comment]
corrigé dans l'image linux 1.1.0
