### ISSUE TITLE
Svxlink se lance a plusieurs reprise. 

### ISSUE THREAD

**Issue by marcbat** [marcbat/svxlinkmanager#39]
Si svxlink se lance à plusieurs reprise, le serveur indique "user already connected" et rejette la seconde requête de connexion.

**Comment by nmermoud** [comment]
Le problème est systématique à chaque reboot pour moi en 2.4.2
Pour le résoudre je passe par une reapplication du profil radio. 
Déconnecter et revenir dans le salon ne résout pas.
Je vois bien 2 instances de svxlink en ssh

**Comment by marcbat** [comment]
Corrigé, c'était lié à un problème dans le scan.
