### ISSUE TITLE
Solution pour le début des sons d'annonces qui sont tronqués

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#4]
L'info viens de José HB9GYR
Le problème peut être réglé en changeant la valeur TX_DELAY de 35 à 900 dans le fichier /etc/spotnik/svxlink.conf
Il ne te reste plus qu'à traduire dans ton interface 🥇

Nathanaël

![2020-11-17_23-21-23](https://user-images.githubusercontent.com/74626991/99457933-0a1e7480-292c-11eb-8312-cd1c82ca4768.jpg)

**Comment by marcbat** [comment]
Corrigé, ça marche. Je déploie ça avec la prochaine release.
