### ISSUE TITLE
La fréquence RX et TX sont inversées

### ISSUE THREAD

**Issue by marcbat** [marcbat/svxlinkmanager#40]

**Comment by nmermoud** [comment]
Tu as trouvé quelque chose à ce sujet ? Je crois que j’ai ouvert ce point à la demande de Enio

**Comment by marcbat** [comment]
Hello, oui, c'est effectivement inversé. Il faut que je corriges ça.

**Comment by marcbat** [comment]
Résolu en 2.2.1
