### ISSUE TITLE
Erreur la première fois qu'on accède au menu mise à jour après une mise à jour depuis 2.2.0

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#44]
On en parle :-)

Nat

LOG de l'erreur :

juin 27 12:33:03 SvxlinkManager svxlinkmanager[10210]: SvxlinkManager.Service.UpdaterService[0] Chargement de la list des release.
juin 27 12:33:03 SvxlinkManager svxlinkmanager[10210]: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100] Unhandled exception rendering component: Value cannot be null. (Parameter 'source') System.ArgumentNullException: Value cannot be null. (Parameter 'source')    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)    at SvxlinkManager.Service.UpdaterService.get_Releases() in /home/vsts/work/1/s/src/SvxlinkManager/Service/UpdaterService.cs:line 95    at SvxlinkManager.Pages.Updater.Manage.BuildRenderTree(RenderTreeBuilder __builder)    at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)    at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)    at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
juin 27 12:33:03 SvxlinkManager svxlinkmanager[10210]: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111] Unhandled exception in circuit 'b_F5C618iuFLioP0aj-KUFCqq43vR2peyqpUHc37mVc'. System.ArgumentNullException: Value cannot be null. (Parameter 'source')    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)    at SvxlinkManager.Service.UpdaterService.get_Releases() in /home/vsts/work/1/s/src/SvxlinkManager/Service/UpdaterService.cs:line 95    at SvxlinkManager.Pages.Updater.Manage.BuildRenderTree(RenderTreeBuilder __builder)    at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)    at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)    at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
juin 27 12:33:03 SvxlinkManager svxlinkmanager[10210]: Microsoft.AspNetCore.Routing.EndpointMiddleware[1] Executed endpoint '/_blazor'
juin 27 12:33:03 SvxlinkManager svxlinkmanager[10210]: Microsoft.AspNetCore.Hosting.Diagnostics[2] Request finished HTTP/1.1 GET http://192.168.1.48/_blazor?id=JlT5j7_oHPrGPZE3WHhgUg - - - 101 - - 15277.4437ms
^C

**Comment by marcbat** [comment]
Corrigé lors de la modification de la page de mise à jour.
