### ISSUE TITLE
On ne peut pas obtenir son ip via la commande DTMF "93#"

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#46]
Le message est "93 commande inconnue"

J'ai identifié le dysfonctionnement qui peut être corrigé comme suit : 

dans le fichier /etc/SvxlinkManager/SvxlinkConfig/Logic.tcl
Adapter la remplacer la ligne : 
set result [exec /etc/spotnik/getIP]
par
set result [exec /etc/SvxlinkManager/getIP]

Créer et éditer le fichier /etc/SvxlinkManager/getIP et ajouter le contenu suivant : 
#!/bin/sh
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'

Le rendre exécutable : 
chmod 755 /etc/SvxlinkManager/getIP

tester en envoyant 93# en DTMF sur le hotspot

**Comment by marcbat** [comment]
Corrigé en 3.1.0
