### ISSUE TITLE
svxlink manager annoncent toujours HB9GXP

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#5]
Bien que j’aie changé mon indicatif sur tous les salons c'est toujours HB9GXP qui s'annonce lors de l'annonce d'indicatif.
Est-ce que tu penses que l'indicatif est défini en dur ailleurs ?

**Comment by marcbat** [comment]
Effectivement il reste la ligne 14 dans le fichier svxlink.conf : CALLSIGN=HB9GXP.

Par contre, ce call n'est pas forcément le même que celui utilisé pour la connexion au svxlink reflector. Je vais devoir ajouter un champs en base de donnée pour la propriété "Call d'annonce".

Il y a également de ligne concernant le CTCSS qu'il faudra que j'édite aussi lors du changement de salon. Ils sont sûrement utilisé pour l'annonce.

**Comment by marcbat** [comment]
Corrigé en 0.10.1
