### ISSUE TITLE
Bouton de commande "Connecter" au wi-fi non fonctionnel

### ISSUE THREAD

**Issue by Criquet** [marcbat/svxlinkmanager#60]
Après avoir configuré le mot de passe d'accès au wi-fi, le bouton "Connecter" est affiché. Cliquer sur ce bouton n'a aucun effet chez moi. J'utilise la version 2.4.3.

**Comment by marcbat** [comment]
Hello, est ce qu'après avoir cliqué sur le bouton Connecter, tu vois apparaitre la mention Configuré? Comme ci dessous.

![image](https://user-images.githubusercontent.com/4466723/129933206-22cf4702-c3f2-4d57-9b22-30ba2dd5f710.png)

**Comment by Criquet** [comment]
Oui, la mention 'Connecté' est bien affichée

Le mer. 18 août 2021 à 18:10, Marc Battaglia ***@***.***> a
écrit :

**Comment by marcbat** [comment]
Attention a bien télécharger la version 3.0.0 de l'image.
