### ISSUE TITLE
Corriger le problème des micros émissions.

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#65]
Passer la valeur de SQL_DELAY à 150 (actuellement elle est à 100)

Contexte : 
Certains Hotspot dans certains environnement déclenchent sans interaction de l'utilisateur des micros émissions.
Ce cas à été détecté avec le hotspot de José car c'était dans son cas très fréquent mais après vérification d'autre hotspot déclenchent également ces micros émissions.
L'augmentation de 50ms de la valeur de "SQL_DELAY" semble résoudre le problème.

**Comment by marcbat** [comment]
Corrigé en 3.1.0
