### ISSUE TITLE
[not_a_issue] configurer le wifi en ligne de commande

### ISSUE THREAD

**Issue by nmermoud** [marcbat/svxlinkmanager#7]
Salut Marc,
Je voulais mettre ces informations dans Wiki mais je pense que je n'ai pas les droits pour créer un article.
Il y a plusieurs manières de configurer le WIFI sous debian mais cette methode me semble pas mal.

Dis moi si ça te suffit.

73'
Nat

### **Verify WIFI interface status :**
_ifconfig -s wlan0_

**Exemple de résultat**
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
wlan0     1500        0      0      0 0             0      0      0      0 BMU

**BMU** # interface is UP
**BM** # interface is DOWN

**Get WIFI interface up and running :**
_ifconfig wlan0 up_

### **Configure WIFI interface for WPA :**

Prerequist : wpasupplicant installed
To install it : _apt-get install wpasupplicant_
To verify it's running : _ps -e | grep wpa_supplicant_

**Commands to make the WPA connexion :**

#Enter CLI
_wpa_cli_

#Get possible commands
_help_

#Scan and list available access points
_scan
scan scan_results_

#Add your AP:
_add_network
set_network 0 ssid "MySSID"
set_network 0 psk "MyPassPhrase"_

#Enable your configuration
_enable_network 0
reconnect_

#Quit GUI
_quit_

#Get Wlan IP
_dhclient -r
dhclient wlan0_

**Comment by marcbat** [comment]
J'ai utilisé network nmcli pour gérer les connexions au wifi.
Résolu en 0.12.0
